export const ADD_ARTICLE_REQUEST = "ADD_ARTICLE_REQUEST"
export const ADD_ARTICLE_DONE = "ADD_ARTICLE_DONE"
export const ADD_ARTICLE_FAILED = "ADD_ARTICLE_FAILED"

export const REMOVE_ARTICLE_REQUEST = "REMOVE_ARTICLE_REQUEST"
export const REMOVE_ARTICLE_DONE = "REMOVE_ARTICLE_DONE"
export const REMOVE_ARTICLE_FAILED = "REMOVE_ARTICLE_FAILED"